### ISSUE TITLE
Segmentation fault when creating box (presentation ipelet)

### ISSUE THREAD

**Issue by lorenzhs** [otfried/ipe#61]
I'm pretty new to ipe so I'm not sure whether the crash is indeed related to tabbed box creation (in https://github.com/otfried/ipelets/blob/master/graph/presentation.lua), but here's a backtrace anyway.

``` c++
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fccc72ebbee in ipe::Fonts::getFace(int) () from /usr/lib/libipecairo.so.7.1.10
[Current thread is 1 (Thread 0x7fccc78f38c0 (LWP 16403))]
(gdb) bt
#0  0x00007fccc72ebbee in ipe::Fonts::getFace(int) () at /usr/lib/libipecairo.so.7.1.10
#1  0x00007fccc72e8c71 in ipe::CairoPainter::opTf() () at /usr/lib/libipecairo.so.7.1.10
#2  0x00007fccc72e94cd in ipe::CairoPainter::execute(ipe::Buffer const&) () at /usr/lib/libipecairo.so.7.1.10
#3  0x00007fccc72e9d21 in ipe::CairoPainter::doDrawText(ipe::Text const*) () at /usr/lib/libipecairo.so.7.1.10
#4  0x00007fccc6e5bb6f in ipe::Text::draw(ipe::Painter&) const () at /usr/lib/libipe.so.7.1.10
#5  0x00007fccc6e583d0 in ipe::Group::draw(ipe::Painter&) const () at /usr/lib/libipe.so.7.1.10
#6  0x00007fccc750a22d in ipe::CanvasBase::drawObjects(_cairo*) () at /usr/lib/libipecanvas.so.7.1.10
#7  0x00007fccc750b4a9 in ipe::CanvasBase::refreshSurface() () at /usr/lib/libipecanvas.so.7.1.10
#8  0x00007fccc750cd4a in ipe::Canvas::paintEvent(QPaintEvent*) () at /usr/lib/libipecanvas.so.7.1.10
#9  0x00007fccc64e4f28 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007fccc64a1ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fccc64a74b6 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fccc5baf5ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fccc64dda19 in QWidgetPrivate::sendPaintEvent(QRegion const&) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007fccc64de061 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fccc64af7f6 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fccc64afa2c in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fccc64cdbbf in QWidgetPrivate::syncBackingStore() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fccc64e4d28 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fccc65fac3b in QMainWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fccc64a1ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fccc64a74b6 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fccc5baf5ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fccc64b015f in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fccc64b0eed in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fccc64d05b2 in QWidget::repaint(QRect const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fccc664175e in QStatusBar::hideOrShow() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fccc664180a in QStatusBar::showMessage(QString const&, int) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x000000000041a44d in AppUi::explain(char const*, int) (this=0x25a3ea0, s=<optimized out>, t=4000)
    at appui_qt.cpp:944
#29 0x0000000000414cc4 in appui_explain(lua_State*) (L=0x2467620) at uilua.cpp:627
#30 0x00007fccc69e0c4d in luaD_precall (L=L@entry=0x2467620, func=<optimized out>, 
    func@entry=0x2569070, nresults=nresults@entry=0) at ldo.c:319
#31 0x00007fccc69ec83d in luaV_execute (L=L@entry=0x2467620) at lvm.c:709
#32 0x00007fccc69e0f8e in luaD_call (L=0x2467620, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at ldo.c:402
#33 0x00007fccc69e05cf in luaD_rawrunprotected (L=L@entry=0x2467620, f=f@entry=0x7fccc69dbb70 <f_call>, ud=ud@entry=0x7ffd55e975c0) at ldo.c:131
#34 0x00007fccc69e11d1 in luaD_pcall (L=L@entry=0x2467620, func=func@entry=0x7fccc69dbb70 <f_call>, u=u@entry=0x7ffd55e975c0, old_top=496, ef=<optimized out>) at ldo.c:603
#35 0x00007fccc69dd0f1 in lua_pcallk (L=L@entry=0x2467620, nargs=nargs@entry=0, nresults=nresults@entry=-1, errfunc=errfunc@entry=1, ctx=ctx@entry=0, k=k@entry=0x7fccc69f06c0 <pcallcont>) at lapi.c:949
#36 0x00007fccc69f0680 in luaB_xpcall (L=0x2467620) at lbaselib.c:405
#37 0x00007fccc69e0c4d in luaD_precall (L=L@entry=0x2467620, func=<optimized out>, 
    func@entry=0x2568d70, nresults=nresults@entry=2) at ldo.c:319
#38 0x00007fccc69ec83d in luaV_execute (L=L@entry=0x2467620) at lvm.c:709
#39 0x00007fccc69e0f8e in luaD_call (L=L@entry=0x2467620, func=<optimized out>, nResults=nResults@entry=0, allowyield=allowyield@entry=0) at ldo.c:402
#40 0x00007fccc69dd02b in lua_callk (L=0x2467620, nargs=nargs@entry=2, nresults=nresults@entry=0, ctx=ctx@entry=0, k=k@entry=0x0) at lapi.c:905
#41 0x0000000000412d59 in AppUiBase::luaAction(ipe::String) (this=this@entry=0x25a3ed0, name=...) at appui.cpp:509
#42 0x000000000041ebfe in AppUi::action(ipe::String) (this=0x25a3ea0, name=...) at appui_qt.cpp:864
#43 0x0000000000419d7c in AppUi::qAction(QString const&) (this=0x25a3ea0, name=...) at appui_qt.cpp:854
#44 0x00000000004226c1 in AppUi::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x25a3ea0, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at moc_appui_qt.cpp:210
#45 0x00007fccc5bddf8a in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007fccc5be8415 in QSignalMapper::mapped(QString const&) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007fccc5be9962 in QSignalMapper::map(QObject*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007fccc5bddf8a in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x00007fccc64983b2 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007fccc649a838 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007fccc661ccd2 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#52 0x00007fccc6622f6c in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007fccc6626ee0 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007fccc64e4f28 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007fccc6627933 in QMenu::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007fccc64a1ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007fccc64a7bb9 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007fccc5baf5ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#59 0x00007fccc64a6ad2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007fccc64ff7dd in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007fccc6501a3b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007fccc64a1ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007fccc64a74b6 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fccc5baf5ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00007fccc5ef1171 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#66 0x00007fccc5ef2e35 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#67 0x00007fccc5ed6e68 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#68 0x00007fccc784f0b0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#69 0x00007fccc3771137 in g_main_context_dispatch (context=0x7fccb40016f0)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3154
#70 0x00007fccc3771137 in g_main_context_dispatch (context=context@entry=0x7fccb40016f0)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3769
#71 0x00007fccc3771390 in g_main_context_iterate (context=context@entry=0x7fccb40016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3840
#72 0x00007fccc377143c in g_main_context_iteration (context=0x7fccb40016f0, may_block=1)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3901
#73 0x00007fccc5c05a3f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#74 0x00007fccc5bacd6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#75 0x00007fccc5bb4e0c in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#76 0x0000000000417739 in mainloop(lua_State*) (L=<optimized out>) at main_qt.cpp:114
#77 0x00007fccc69e0c4d in luaD_precall (L=L@entry=0x2467620, func=<optimized out>, 
    func@entry=0x2568d10, nresults=nresults@entry=0) at ldo.c:319
#78 0x00007fccc69ec83d in luaV_execute (L=L@entry=0x2467620) at lvm.c:709
#79 0x00007fccc69e0f8e in luaD_call (L=L@entry=0x2467620, func=<optimized out>, nResults=nResults@entry=1, allowyield=allowyield@entry=0) at ldo.c:402
#80 0x00007fccc69dd02b in lua_callk (L=L@entry=0x2467620, nargs=nargs@entry=2, nresults=nresults@entry=1, ctx=ctx@entry=0, k=k@entry=0x0) at lapi.c:905
#81 0x00007fccc69f7f17 in ll_require (L=0x2467620) at loadlib.c:520
#82 0x00007fccc69e0c4d in luaD_precall (L=L@entry=0x2467620, func=<optimized out>, 
    func@entry=0x2467930, nresults=nresults@entry=0) at ldo.c:319
#83 0x00007fccc69ec83d in luaV_execute (L=L@entry=0x2467620) at lvm.c:709
#84 0x00007fccc69e0f8e in luaD_call (L=0x2467620, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at ldo.c:402
#85 0x00007fccc69e05cf in luaD_rawrunprotected (L=L@entry=0x2467620, f=f@entry=0x7fccc69dbb70 <f_call>, ud=ud@entry=0x7ffd55e98c70) at ldo.c:131
#86 0x00007fccc69e11d1 in luaD_pcall (L=L@entry=0x2467620, func=func@entry=0x7fccc69dbb70 <f_call>, u=u@entry=0x7ffd55e98c70, old_top=48, ef=<optimized out>) at ldo.c:603
#87 0x00007fccc69dd0f1 in lua_pcallk (L=L@entry=0x2467620, nargs=nargs@entry=0, nresults=nresults@entry=0, errfunc=errfunc@entry=-2, ctx=ctx@entry=0, k=k@entry=0x0) at lapi.c:949
#88 0x000000000040f678 in main(int, char**) (fn=0x417730 <mainloop(lua_State*)>, L=0x2467620) at main_common.i:93
#89 0x000000000040f678 in main(int, char**) (argc=2, argv=<optimized out>) at main_qt.cpp:137
```

Output of `thread apply all bt full`: https://gist.github.com/lorenzhs/c6ab5db144a69ada000f9fd446c248d2

Please let me know if you need more info

**Comment by otfried** [comment]
The crash happens when loading a font - one possible reason could be that the font map is wrong.

This part of Ipe has changed a lot after version 7.1.10, so I cannot look into a problem with this old version.  Please try 7.2.2 and see if you still have a problem.

On the other hand, I don't know how compatible this ipelet is with the different Ipe versions. The last version mentioned there is 7.1.8...

**Comment by lorenzhs** [comment]
Thanks, but I can't even reproduce with 7.1.10, this seems to be a bit spurious. If the backtrace isn't of much help, I'll just get back to you if I hit this again or manage to reproduce it, and assume it's either a problem with the ipelet or my old version of ipe if not ;)
