### ISSUE TITLE
Segfault due to missing length check when creating empty paragraph

### ISSUE THREAD

**Issue by lorenzhs** [otfried/ipe#64]
This one is an actual, real bug that doesn't only occur under weird circumstances :) I've reproduced it with Ipe 7.2.2.

Steps to reproduce: In any document (may be blank), create a paragraph (the tool with the "G" shortcut), and don't enter any text. When clicking "OK" to close the dialog, Ipe segfaults in `createLatexSource`:

``` cpp
Program received signal SIGSEGV, Segmentation fault.
ipe::Latex::createLatexSource (this=this@entry=0x7fffffffc750, stream=..., preamble=...) at ipelatex.cpp:246
246       if (txt[txt.size() - 1] != '\n')
(gdb) bt
#0  0x00007ffff7f8a9c3 in ipe::Latex::createLatexSource(ipe::Stream&, ipe::String) (this=this@entry=0x7fffffffc750, stream=..., preamble=...) at ipelatex.cpp:246
#1  0x00007ffff7f8cba0 in ipe::Document::runLatex(ipe::String&) (this=0x7c7f90, texLog=...) at ipedoc.cpp:767
#2  0x00007ffff7fb5c46 in document_runLatex(lua_State*) (L=0x44d000) at ipelib.cpp:295
#3  0x00007ffff7bb4c4d in luaD_precall (L=L@entry=0x44d000, func=<optimized out>, 
    func@entry=0x4f0600, nresults=nresults@entry=4) at ldo.c:319
#4  0x00007ffff7bc083d in luaV_execute (L=L@entry=0x44d000) at lvm.c:709
#5  0x00007ffff7bb4f8e in luaD_call (L=L@entry=0x44d000, func=<optimized out>, nResults=nResults@entry=0, allowyield=allowyield@entry=0) at ldo.c:402
#6  0x00007ffff7bb102b in lua_callk (L=0x44d000, nargs=<optimized out>, nresults=0, ctx=<optimized out>, k=<optimized out>) at lapi.c:905
#7  0x00007ffff76b936f in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff7675ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff767bbb9 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff6d835ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff767aad2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff76d347b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff76d5a3b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7675ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff767b4b6 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff6d835ab in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff70c5171 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#18 0x00007ffff70c6e35 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#19 0x00007ffff70aae68 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#20 0x00007fffedbb10b0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#21 0x00007ffff4945137 in g_main_context_dispatch (context=0x7fffe40016f0)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3154
#22 0x00007ffff4945137 in g_main_context_dispatch (context=context@entry=0x7fffe40016f0)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3769
#23 0x00007ffff4945390 in g_main_context_iterate (context=context@entry=0x7fffe40016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3840
#24 0x00007ffff494543c in g_main_context_iteration (context=0x7fffe40016f0, may_block=1)
    at /build/glib2.0-2CrUwg/glib2.0-2.48.0/./glib/gmain.c:3901
#25 0x00007ffff6dd9a3f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6d80d6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff6d88e0c in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x0000000000415e59 in  ()
#29 0x00007ffff7bb4c4d in luaD_precall (L=L@entry=0x44d000, func=<optimized out>, 
    func@entry=0x4f0440, nresults=nresults@entry=0) at ldo.c:319
#30 0x00007ffff7bc083d in luaV_execute (L=L@entry=0x44d000) at lvm.c:709
#31 0x00007ffff7bb4f8e in luaD_call (L=L@entry=0x44d000, func=<optimized out>, nResults=nResults@entry=1, allowyield=allowyield@entry=0) at ldo.c:402
#32 0x00007ffff7bb102b in lua_callk (L=L@entry=0x44d000, nargs=nargs@entry=2, nresults=nresults@entry=1, ctx=ctx@entry=0, k=k@entry=0x0) at lapi.c:905
#33 0x00007ffff7bcbf17 in ll_require (L=0x44d000) at loadlib.c:520
#34 0x00007ffff7bb4c4d in luaD_precall (L=L@entry=0x44d000, func=<optimized out>, 
    func@entry=0x44d310, nresults=nresults@entry=0) at ldo.c:319
#35 0x00007ffff7bc083d in luaV_execute (L=L@entry=0x44d000) at lvm.c:709
#36 0x00007ffff7bb4f8e in luaD_call (L=0x44d000, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at ldo.c:402
#37 0x00007ffff7bb45cf in luaD_rawrunprotected (L=L@entry=0x44d000, f=f@entry=0x7ffff7bafb70 <f_call>, ud=ud@entry=0x7fffffffd8e0) at ldo.c:131
#38 0x00007ffff7bb51d1 in luaD_pcall (L=L@entry=0x44d000, func=func@entry=0x7ffff7bafb70 <f_call>, u=u@entry=0x7fffffffd8e0, old_top=48, ef=<optimized out>) at ldo.c:603
#39 0x00007ffff7bb10f1 in lua_pcallk (L=0x44d000, nargs=<optimized out>, nresults=0, errfunc=<optimized out>, ctx=<optimized out>, k=<optimized out>) at lapi.c:949
#40 0x000000000040eba4 in  ()
#41 0x00007ffff57b7610 in __libc_start_main (main=
    0x40e7e0, argc=1, argv=0x7fffffffda78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda68) at libc-start.c:291
#42 0x000000000040ec79 in  ()
```

That lacks a check if `txt.size() == 0` leading to the out-of-bounds segfault.

Thanks for all the hard work creating Ipe, I really appreciate it even though the volume of weird issues I'm filing here may be a bit annoying!

**Comment by otfried** [comment]
Fixed in 7.2.3.
